'''A dictionary to store token types'''
TOKEN_TYPES = {
    "PRINT_COMMAND": 'PRINT_COMMAND',
    "STRING_LITERAL": 'STRING_LITERAL',
    "INTEGER_LITERAL": 'INTEGER_LITERAL',
    "FLOAT_LITERAL": 'FLOAT_LITERAL',
    "BOOLEAN_LITERAL": 'BOOLEAN_LITERAL',
    "NONE_LITERAL": 'NONE_LITERAL',
    "LIST_START": 'LIST_START',
    "LIST_END": 'LIST_END',
    "DICT_START": 'DICT_START',
    "DICT_END": 'DICT_END',
    "COMMA": 'COMMA',
    "COLON": 'COLON',
    "VARIABLE_DECLARE": 'VARIABLE_DECLARE',
    "IDENTIFIER": 'IDENTIFIER',
    "EQUALS": 'EQUALS',
    "UNKNOWN": 'UNKNOWN'
}